[package]
name = "regression"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.1"
ndarray = "0.15.6"
rurel = "0.6.0"
linfa = "0.7.1"
linfa-linear = "0.7.1"
csv = "1.3.0"